--1.
SELECT *
FROM JOB;

--2. 
SELECT JOB_NAME
FROM JOB;

--3.
SELECT *
FROM DEPARTMENT;

--4. 
SELECT EMP_NAME, EMAIL, PHONE, HIRE_DATE
FROM EMPLOYEE;

--5.
SELECT HIRE_DATE, EMP_NAME, SALARY
FROM EMPLOYEE;

--6.
SELECT HIRE_DATE, SALARY * 12 AS 연봉, SALARY * (NVL(BONUS, 0) + 1) * 12 AS 총수령액,
       (SALARY * (NVL(BONUS, 0) + 1) * 12) * 0.97 AS 실수령액
FROM EMPLOYEE;

--7.
SELECT EMP_NAME, SALARY, HIRE_DATE, PHONE
FROM EMPLOYEE
WHERE SALARY BETWEEN 6000000 AND 10000000;

--8.
SELECT EMP_NAME, SALARY, (SALARY * (NVL(BONUS, 0) + 1) * 12) * 0.97 AS 실수령액, HIRE_DATE
FROM EMPLOYEE
WHERE (SALARY * (NVL(BONUS, 0) + 1) * 12) * 0.97 >= 50000000;

--9.
SELECT *
FROM EMPLOYEE
WHERE SALARY >= 4000000 AND JOB_CODE = 'J2';

--10.
SELECT EMP_NAME, DEPT_CODE, HIRE_DATE
FROM EMPLOYEE
WHERE DEPT_CODE IN ('D9', 'D5') AND HIRE_DATE < '02/01/01';

--11.
SELECT *
FROM EMPLOYEE
WHERE HIRE_DATE BETWEEN '90/01/01' AND '01/01/01';

--12.
SELECT EMP_NAME
FROM EMPLOYEE
WHERE EMP_NAME LIKE ('%연');

--13. 
SELECT EMP_NAME, PHONE
FROM EMPLOYEE
WHERE PHONE NOT LIKE ('010%');

--14. 
SELECT *
FROM EMPLOYEE
WHERE EMAIL LIKE '____\_%' ESCAPE '\' AND DEPT_CODE IN ('D9', 'D6') AND 
      HIRE_DATE BETWEEN '90/01/01' AND '00/12/01' AND SALARY >= 2700000;
      
--15.EXTRACT(YEAR FROM )
SELECT EMP_NAME, EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO, 1 , 6))),
EXTRACT(MONTH FROM TO_DATE(SUBSTR(EMP_NO, 1 , 6))),
EXTRACT(DAY FROM TO_DATE(SUBSTR(EMP_NO, 1 , 6)))
FROM EMPLOYEE;

--16.
SELECT EMP_NAME, RPAD(SUBSTR(EMP_NO, 1, INSTR(EMP_NO, '-')), LENGTH(EMP_NO), 'X')
FROM EMPLOYEE;

--17.
SELECT EMP_NAME, ABS(TRUNC(HIRE_DATE - SYSDATE)) AS 근무일수1, TRUNC(SYSDATE - HIRE_DATE) AS 근무일수2
FROM EMPLOYEE;

--18.
SELECT *
FROM EMPLOYEE
WHERE MOD(EMP_ID, 2) = 1;

--19.
SELECT *
FROM EMPLOYEE
WHERE EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM HIRE_DATE) >= 20;

--20.
SELECT EMP_NAME, TO_CHAR(SALARY, 'L99,999,999')
FROM EMPLOYEE;

--21.
SELECT EMP_NAME, DEPT_CODE, 
SUBSTR(EMP_NO, 1, 2) || '년' || SUBSTR(EMP_NO, 3, 2) || '월' || SUBSTR(EMP_NO, 5, 2) || '일', 
EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO, 1, 6)))
FROM EMPLOYEE;

--22.
SELECT EMP_NAME, DECODE(DEPT_CODE, 'D5', '총무부', 'D6', '기획부', 'D9', '영업부', NULL) AS "부서이름"
FROM EMPLOYEE
WHERE DEPT_CODE IN ('D5','D6','D9')
ORDER BY DEPT_CODE;

--23.
SELECT EMP_NAME, SUBSTR(EMP_NO, 1, 6), SUBSTR(EMP_NO, 8, 15), SUBSTR(EMP_NO, 1, 6) + SUBSTR(EMP_NO, 8, 15)
FROM EMPLOYEE
WHERE EMP_ID = 201;

--24.
SELECT SUM(SALARY * (NVL(BONUS, 0) + 1) * 12)
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5';

--25.

SELECT COUNT(EMP_ID) AS "전체 직원 수", 
COUNT(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE) = 2001 THEN '1'
            ELSE NULL
            END) AS "2001년",
    COUNT(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE) = 2002 THEN '2'
            ELSE NULL
            END) AS "2002년",
    COUNT(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE) = 2003 THEN '3'
            ELSE NULL
            END) AS "2003년",
    COUNT(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE) = 2004 THEN '4'
            ELSE NULL
            END) AS "2004년"
FROM EMPLOYEE;