CREATE TABLE TEST(
    NUM NUMBER,
    NAME VARCHAR2(15),
    BIRTH DATE
);

SET AUTOCOMMIT OFF;


SELECT *
FROM TEST;

CREATE TABLE USER(
    USER_ID VARCHAR2(30) PRIMARY KEY,
    USER_PWD VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    ENROLL_DATE DATE
);


CREATE TABLE STUFF(
    USER_ID VARCHAR2(30) REFERENCES USER(USER_ID) PRIMARY KEY,
    STUFF_NAME VARCHAR2(30),
    STUFF_CATEGORY VARCHAR2(30)
);