CREATE TABLE TEST(
    NUM NUMBER,
    NAME VARCHAR2(15),
    BIRTH DATE
);

SET AUTOCOMMIT OFF;


SELECT *
FROM TEST;

CREATE TABLE USERS(
    USER_ID VARCHAR2(30) PRIMARY KEY,
    USER_PWD VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    ENROLL_DATE DATE
);

drop table STUFF;
CREATE TABLE STUFF(
    USER_ID VARCHAR2(30),
    STUFF_NAME VARCHAR2(30),
    STUFF_CATEGORY VARCHAR2(30),
    KEEP_DATE DATE
);