CREATE USER HW IDENTIFIED BY HW;

GRANT CONNECT, RESOURCE, CREATE VIEW TO HW;

--1. BASIC SELECT

--1)
SELECT DEPARTMENT_NAME AS "학과 명", CATEGORY AS "계열"
FROM TB_DEPARTMENT;

--2)
SELECT CONCAT(DEPARTMENT_NAME, CONCAT('의 정원은 ', CONCAT(CAPACITY, '명 입니다.'))) 
        AS "학과별 정원"
FROM TB_DEPARTMENT;

--3)
SELECT STUDENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과' AND SUBSTR(STUDENT_SSN, 8, 1) IN (2,4)
    AND ABSENCE_YN = 'Y';
    
--4)
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NAME DESC;

--5)
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

--6)
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--7)
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

--8)
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--9)
SELECT CATEGORY
FROM TB_DEPARTMENT
GROUP BY CATEGORY
ORDER BY CATEGORY;

--10)
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'N' AND TO_CHAR(ENTRANCE_DATE, 'YY') = '02' 
    AND STUDENT_ADDRESS LIKE ('%전주%');