--4. DDL

--1) 
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

--2)
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

--3)
ALTER TABLE TB_CATEGORY ADD PRIMARY KEY (NAME);

--4)
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;

--5)
ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR2(10);
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR2(20);

--6)
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_TYPE_NO;
ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;

--7)
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN CLASS_TYPE_NO TO PK_CLASS_TYPE_NO;
ALTER TABLE TB_CATEGORY RENAME COLUMN CATEGORY_NAME TO PK_CATEGORY_NAME;

--8)
INSERT INTO TB_CATEGORY VALUES ('공학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('의학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('예체능', 'Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회', 'Y');
COMMIT;

--9)
ALTER TABLE TB_DEPARTMENT  ADD CONSTRAINT FK_DEPARTMENT_CATEGORY 
FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY (PK_CATEGORY_NAME);

--10)
CREATE VIEW VW_학생일반정보
AS
    SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "학생이름", STUDENT_ADDRESS AS "주소"
    FROM TB_STUDENT;
    
--11)
CREATE VIEW VW_지도면담
AS
    SELECT STUDENT_NAME AS "학생이름", DEPARTMENT_NAME AS "학과이름", PROFESSOR_NAME AS "지도교수이름"
    FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
    ORDER BY DEPARTMENT_NAME
;

--12)
CREATE VIEW VW_학과별학생수
AS
    SELECT DEPARTMENT_NAME, COUNT(*) AS STUDENT_COUNT
    FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
    GROUP BY DEPARTMENT_NAME
    ORDER BY DEPARTMENT_NAME
;

--13)
UPDATE VW_학생일반정보
SET 학생이름 = '윤대한'
WHERE "학번" = 'A213046';

--14)
/*
    1) 뷰에 정의되어있지 않은 컬럼을 조작하려고 하는 경우
    2) 뷰에 정의되어있지 않은 컬럼 중에 베이스테이블 상에 NOT NULL제약조건이 지정되어있는 경우
    3) 산술연산식이나 함수식을 사용한 경우
    4) 그룹함수나 GROUP BY절을 포함한 경우
    5) DISTINCT구문이 포함된 경우
    6) JOIN을 이용해서 여러 테이블을 연결시켜놓은 경우
*/

--15)
SELECT CLASS_NO, CLASS_NAME, "누적수강생수(명)"
FROM (SELECT CLASS_NO, CLASS_NAME, COUNT(CLASS_NO) AS "누적수강생수(명)"
        FROM (SELECT *
                FROM TB_CLASS
                JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
                JOIN TB_GRADE USING (CLASS_NO)
                WHERE SUBSTR(TERM_NO, 1, 4) >= 2005)
        GROUP BY CLASS_NO, CLASS_NAME
        ORDER BY "누적수강생수(명)" DESC)
WHERE ROWNUM <= 3;
                
                