--2. ADDITIONAL SELECT - 함수

--1)
SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 이름, 
        TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') AS 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY EXTRACT(YEAR FROM ENTRANCE_DATE);

--2)
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE ('___');

--3)
SELECT PROFESSOR_NAME AS 교수이름, 
CASE 
    WHEN
        TO_CHAR(SYSDATE, 'MMDD') <= SUBSTR(PROFESSOR_SSN, 3,4)
        THEN
            TO_CHAR(SYSDATE, 'YYYY') - CONCAT(19,SUBSTR(PROFESSOR_SSN, 1,2))
        ELSE
            TO_CHAR(SYSDATE, 'YYYY') - CONCAT(19,SUBSTR(PROFESSOR_SSN, 1,2)) -1
        END AS 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8,1) = 1
ORDER BY SUBSTR(PROFESSOR_SSN, 1,2) DESC;

--4)
SELECT SUBSTR(PROFESSOR_NAME, 2) AS 이름
FROM TB_PROFESSOR;

--5)
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE TO_CHAR(ENTRANCE_DATE, 'YYYY') - 
CASE
    WHEN
        SUBSTR(STUDENT_SSN, 1,2) - TO_CHAR(SYSDATE, 'YY') > 0
        THEN
            CONCAT('19', SUBSTR(STUDENT_SSN,1,2))
        ELSE
            CONCAT('20', SUBSTR(STUDENT_SSN,1,2))
        END
    > 19;
    
--6)
SELECT TO_CHAR(TO_DATE(20201225), 'DAY')
FROM DUAL;

--7) 2099, 2049, 1999, 2049
SELECT TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'), 'YYYY/MM/DD'),
        TO_CHAR(TO_DATE('49/10/11', 'YY/MM/DD'), 'YYYY/MM/DD'),
        TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'), 'YYYY/MM/DD'),
        TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'), 'YYYY/MM/DD')
FROM DUAL;

--8)
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE ('A%');

--9)
SELECT ROUND(AVG(POINT), 1) AS 평점
FROM TB_GRADE
JOIN TB_STUDENT USING (STUDENT_NO)
GROUP BY STUDENT_NO
HAVING STUDENT_NO = 'A517178';

--10)
SELECT DEPARTMENT_NO AS 학과번호,  COUNT(STUDENT_NO) AS "학생수(명)"
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING (DEPARTMENT_NO)
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--11)
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12)
SELECT SUBSTR(TERM_NO, 1,4) AS 년도, ROUND(AVG(POINT), 1) AS "년도 별 평점"
FROM (SELECT *
        FROM TB_GRADE
        WHERE STUDENT_NO = 'A112113')
GROUP BY SUBSTR(TERM_NO, 1,4)
ORDER BY SUBSTR(TERM_NO, 1,4);

--13)
SELECT DEPARTMENT_NO AS 학과코드명, COUNT(*) AS "휴학생 수"
FROM (SELECT *
        FROM TB_STUDENT
        WHERE ABSENCE_YN = 'Y')
GROUP BY DEPARTMENT_NO
UNION
(SELECT DEPARTMENT_NO AS 학과코드명, COUNT(NULL) AS "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
MINUS
SELECT DEPARTMENT_NO AS 학과코드명, COUNT(NULL) AS "휴학생 수"
FROM (SELECT *
        FROM TB_STUDENT
        WHERE ABSENCE_YN = 'Y')
GROUP BY DEPARTMENT_NO);

--14)
SELECT STUDENT_NAME AS "동일이름", COUNT(STUDENT_NAME) AS "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME) > 1
ORDER BY STUDENT_NAME;

--15)
SELECT SUBSTR(TERM_NO, 1,4) AS 년도, SUBSTR(TERM_NO, 5,2) AS 학기, POINT AS 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
UNION
SELECT SUBSTR(TERM_NO, 1,4) AS 년도, '' AS 학기, ROUND(AVG(POINT), 1) AS 평점
FROM (SELECT *
        FROM TB_GRADE
        WHERE STUDENT_NO = 'A112113')
GROUP BY SUBSTR(TERM_NO, 1,4)
UNION
SELECT NULL AS 년도, NULL AS 학기, ROUND(AVG(POINT), 1) AS 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113';
